Users/cory miller/git user and email
actions/checkout pull request #1707
Opened 2024-04-25 20:07 UTC by cory-miller

2024-04-25 20:29 UTC, jeffwidman approved these changes

2024-04-25 22:16 UTC, joshmgross commented on README.md
> +          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
We should clarify that this configuration is only valid for github.com - other instances like GHES will have a different ID here.

2024-04-29 18:28 UTC, cory-miller commented on README.md
> +          git config user.name "github-actions[bot]"
```suggestion
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
```

2024-04-29 20:49 UTC, joshmgross approved these changes

2024-04-29 23:19 UTC, Magdihamed requested changes
/

2024-04-30 15:50 UTC, merged

2024-04-30 16:48 UTC, Magdihamed commented on README.md
> +          git config user.name "github-actions[bot]"
r/magdi hamed عمل جيد 👏

2024-05-07 04:53 UTC, szepeviktor commented
The user ID can be obtained from GitHub's API.
https://api.github.com/users/github-actions%5Bbot%5D