Pin actions/checkout's own workflows to a known, good, stable version.
actions/checkout pull request #1776
Opened 2024-06-12 15:53 UTC by jww3

Dependabot tried to update our internal CI workflows to the bleeding edge.  

It's safer to pin these to a specific version to reduce the number of hoops we have to jump through in the event of a bad release.

2024-06-12 17:10 UTC, joshmgross approved these changes

2024-06-12 17:11 UTC, merged

2024-10-01 01:50 UTC, ratchanonsuttawas approved these changes
6ccd57f4c5d15bdc2fef309bd9fb6cc9db2ef1c6

2024-10-01 01:50 UTC, ratchanonsuttawas approved these changes

2024-10-01 01:50 UTC, ratchanonsuttawas requested changes
+13 -13

2024-10-01 01:51 UTC, ratchanonsuttawas reviewed
>Commit 823fceebd3c828b59f34cc61bc401de251e8897f